export enum CysyncError {
  UNKNOWN_FLOW_ERROR = 'DS_MISC_5500',
  CUSTOM_ERROR = 'DS_MISC_5501',

  NETWORK_ERROR = 'DS_CONN_3001',
  NETWORK_FAILURE = 'DS_CONN_3002',
  NETWORK_UNREACHABLE = 'DS_CONN_2001',

  DEVICE_AUTH_FAILED = 'HD_SEC_0001',
  DEVICE_AUTH_REJECTED = 'HD_UACT_1504',

  DEVICE_UPGRADE_REJECTED = 'HD_UACT_1505',
  DEVICE_UPGRADE_FIRMWARE_DOWNLOAD_FAILED = 'HD_FIRM_5001',
  DEVICE_UPGRADE_FAILED = 'HD_FIRM_5002',
  DEVICE_UPGRADE_CONNECTION_FAILED_IN_AUTH = 'HD_FIRM_5501',

  DEVICE_NOT_READY = 'HD_COM_1001',
  DEVICE_NOT_READY_IN_INITIAL = 'HD_COM_1002'
}
